apiVersion: traefik.io/v1alpha1 # traefik.containo.us/v1alpha1 depreciated in Traefik v3
kind: Middleware
metadata:
  name: headers
  namespace: teckshop-prod
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https