apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: catalog-api=ghcr.io/captainpowerturtle/teckshop/catalog.api:x.x.x
    argocd-image-updater.argoproj.io/catalog-api.update-strategy: semver
    argocd-image-updater.argoproj.io/catalog-api.allow-tags: regexp:^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
    argocd-image-updater.argoproj.io/catalog-api.helm.image-name: containers.image.name
    argocd-image-updater.argoproj.io/catalog-api.helm.image-tag: containers.image.tag
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: teckshop-prod
    name: in-cluster
  project: default
  source:
    path: deployment/helm/services/catalog
    repoURL: git@github.com:CaptainPowerTurtle/TeckShop.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
